# Generated by Django 5.2.9 on 2025-12-26 08:23

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=100, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='عنوان محصول')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت محصول (تومان)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر محصول')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='عنوان خدمات')),
                ('image', models.ImageField(upload_to='services/', verbose_name='تصویر خدمات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت خدمات (تومان)')),
                ('description', models.TextField(verbose_name='توضیحات خدمات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': 'خدمات',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('date', django_jalali.db.models.jDateField(verbose_name='تاریخ رزرو')),
                ('time', models.TimeField(verbose_name='ساعت رزرو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api_module.service', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'unique_together': {('date', 'time')},
            },
        ),
    ]
