# Generated by Django 5.2.9 on 2025-12-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='media/gallery/', verbose_name='تصویر'),
        ),
    ]
