# Generated by Django 5.2.9 on 2025-12-26 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0002_alter_gallery_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
