# Generated by Django 5.2.9 on 2025-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0003_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(db_index=True, max_length=100, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
    ]
