# Generated by Django 5.2.9 on 2025-12-29 05:30

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0006_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'رزرو', 'verbose_name_plural': 'رزروها'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ رزرو'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(verbose_name='ساعت رزرو'),
        ),
    ]
