# Generated by Django 5.2.9 on 2025-12-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0009_alter_reservation_options_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
