# Generated by Django 5.2.9 on 2025-12-29 12:39

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0010_alter_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(choices=[('10-12', '۱۰ تا ۱۲'), ('12-14', '۱۲ تا ۱۴'), ('14-16', '۱۴ تا ۱۶'), ('16-18', '۱۶ تا ۱۸'), ('18-20', '۱۸ تا ۲۰')], max_length=10, verbose_name='ساعت'),
        ),
    ]
