# Generated by Django 5.2.9 on 2025-12-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_module', '0012_alter_reservation_date_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.CharField(max_length=5),
        ),
    ]
