# Generated by Django 5.2.9 on 2025-12-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پیام')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کاربر')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره تماس کاربر')),
                ('message', models.TextField(verbose_name='پیام کاربر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
    ]
